samd21:
	cd samd21 && $(MAKE) all

samv71:
	cd samv71 && $(MAKE) all

linux:
	cd linux && $(MAKE) all

clean:
	cd samd21 && $(MAKE) clean
	cd samv71 && $(MAKE) clean
	cd linux && $(MAKE) clean

.PHONY: samv71 samd21 linux clean
